[build.environment]
GO_VERSION = "1.25.3"
HUGO_VERSION = "0.152.2"
NODE_VERSION = "22.20.0"
TAILWINDCSS_VERSION = "v4.1.17"
TZ = "America/Toronto"

[build]
publish = "public"
command = """\
    # Download Tailwind standalone binary for Linux
    curl -sL -o tailwindcss "https://github.com/tailwindlabs/tailwindcss/releases/download/${TAILWINDCSS_VERSION}/tailwindcss-linux-x64" && \
    # Create a local bin directory and move the binary there
    mkdir -p "${HOME}/.local/bin" && \
    mv tailwindcss "${HOME}/.local/bin/tailwindcss" && \
    chmod +x "${HOME}/.local/bin/tailwindcss" && \
    # Put that bin dir on PATH so Hugo's css.TailwindCSS can find `tailwindcss`
    export PATH=\"${HOME}/.local/bin:${PATH}\" && \
    # (optional, same as Hugo docs)
    git config core.quotepath false && \
    # Now build the site with Hugo (which will invoke tailwindcss)
    hugo --gc --minify --baseURL \"${URL}\"
  """
