[build.environment]
GO_VERSION = "1.25.3"
HUGO_VERSION = "0.152.2"
NODE_VERSION = "22.20.0"
TZ = "America/Toronto"

[build]
publish = "public"
command = """\
  # Download Tailwind standalone binary
  curl -sL -o tailwindcss "https://github.com/tailwindlabs/tailwindcss/releases/download/v4.1.17/tailwindcss-linux-x64" && \
  chmod +x tailwindcss && \
  # Build Tailwind CSS
  ./tailwindcss -i ./assets/css/tailwind.css -o ./static/css/tailwind.css --minify && \
  # Build Hugo
  hugo --gc --minify --baseURL "${URL}"
"""
